### ISSUE TITLE
Missing dependency backports.strenum?

### ISSUE THREAD

**Issue by pawamoy** [conda-forge/griffe-feedstock#109]
Hello, Griffe author here. v0.48 depends on backports.strenum for Python less than 3.11. It seems that the Conda package doesn't declare this dependency. Can this be fixed here, or do I have to do something in Griffe?

See https://github.com/mkdocstrings/griffe/issues/307.

**Comment by pawamoy** [comment]
Thanks to maintainers of this repo btw ^^

**Comment by bandersen23** [comment]
That was missed in the automatic conda-forge update which I will look into. I normally check the merged PRs shortly after but just saw these. I apologize for that. But I’ve added it in the above PR that will be merged soon.

**Comment by bandersen23** [comment]
This should be merged into the recipe as a build update. So people just need to update griffe and they’ll get this fix. Again, I apologize for missing this.

**Comment by pawamoy** [comment]
No need to apologize!! Thank you very much for maintaining the Conda recipe!

**Comment by bandersen23** [comment]
No problem! I'm leaving this open as I'll likely add it as a conditional dependency based on Python version, just need to do some testing of that build first.

**Comment by pawamoy** [comment]
Don't bother, because in fact I'll most probably remove the dependency. `StrEnum` is achievable by inheriting from both `str` and `Enum`, so we won't need the backport. Next version will remove the dependency to backports.strenum. Sorry for the trouble (I thought you'd have seen my messages in the linked issue while I was afk).

I'm running some tests right now, let me confirm all this in a minute.

**Comment by pawamoy** [comment]
Oops, forgot to confirm: yup, the dependency will be removed in next version. Sorry again for the back and forth ^^ and thanks for your help :)
