### ISSUE TITLE
Deprecated submodules 

### ISSUE THREAD

**Issue by pawamoy** [conda-forge/griffe-feedstock#111]
v0.48 deprecated all submodules. All objects are now exposed in the top level `griffe` module. The recipe should therefore be updated, notably `build.entrypoints` and `tests.imports`. The submodules will be removed in v1 so the recipe would fail then ^^

**Comment by bandersen23** [comment]
Thank you for the notice! I saw that in 0.48 and will create a local update and ensure it all packages correctly. It’ll take me a day or two to do that. Thanks!

**Comment by pawamoy** [comment]
Perfect, thank you! And there is no rush, take all the time you need :slightly_smiling_face:
